GetTerminus/terminus-ui

karma.conf.js
The wrong version number was published to NPM (0.0.0-development)
=> fix(CI): fake change to trigger a new release

package.json, src/lib/index.ts
The package.json is being copied over and I believe the files array is affecting publish
=> fix(CI): remove files array and publish the build dir

README.md, package.json, tooling/setup.js
Added a new setup script and accompanying "yarn run" command which will run "yarn install" in the root as well as any subdirectories containing a "package.json file" utilizing perform a recursive breadth first directory traversal.
=> chore: Added a new setup script and accompanying yarn run command

src/demo/src/app/components/login-form.component.ts, src/lib/src/login-form/login-form.component.html, src/lib/src/login-form/login-form.component.ts
Added a new 'isRedirecting' flag to the login form component, which when true will cause the submit button of that form to exhibit an 'in progress' state.
ticket :https://www.pivotaltracker.com/story/show/150633635
(note: This does not complete the ticket, it's just a part of it)
=> feat: Added isRedirecting input flag to login form component.

.codecov.yml, karma.conf.js, src/demo/src/app/components/copy.component.ts, src/lib/index.ts, src/lib/src/button/button.component.spec.ts, src/lib/src/button/button.component.ts, src/lib/src/copy/copy.component.spec.ts, src/lib/src/copy/copy.component.ts, src/lib/src/copy/copy.module.ts, src/lib/src/loading-overlay/loading-overlay.directive.spec.ts, src/lib/src/login-form/login-form.component.spec.ts, src/lib/src/menu/menu.component.spec.ts, src/lib/src/module.ts, src/lib/src/navigation/navigation.component.spec.ts, src/lib/src/pagination/pagination.component.spec.ts, src/lib/src/pagination/pagination.component.ts, src/lib/src/services/document/document.service.mock.ts, src/lib/src/services/document/document.service.spec.ts, src/lib/src/services/document/document.service.ts, src/lib/src/toggle/toggle.component.spec.ts, src/lib/src/toggle/toggle.component.ts, src/lib/src/utilities/reactive-form-base.component.spec.ts, src/lib/src/utilities/reactive-form-base.component.ts, src/lib/src/validation-messages/validation-messages.component.spec.ts, src/lib/src/validation-messages/validation-messages.component.ts, tooling/karma-test-shim.js
- increase code coverage for project
- currently still have 3 branches that aren't covered, but I cannot figure out how to test them.
- increased the default delay for collapsing buttons
- no longer including `mock` files in coverage report
- now generating HTML coverage results to allow devs to check coverage before creating a PR
- create document service
=> Increase code coverage

src/lib/src/login-form/login-form.component.html
=> fix(LoginForm): Verified autofill works for email/password

LICENSE, src/demo/src/app/components/button.component.ts, src/demo/src/app/components/pagination.component.ts, src/lib/src/button/button.component.scss, src/lib/src/button/button.component.spec.ts, src/lib/src/button/button.component.ts, src/lib/src/pagination/pagination.component.spec.ts, src/lib/src/pagination/pagination.component.ts
- pagination now supports dynamic record count messages with a custom template
- button's are no longer encapsulated
=> Update pagination and button

src/demo/package.json, src/demo/yarn.lock, src/lib/src/button/button.component.html, src/lib/src/button/button.component.ts, src/lib/src/checkbox/checkbox.component.html, src/lib/src/checkbox/checkbox.component.ts, src/lib/src/input/input.component.html, src/lib/src/input/input.component.ts, src/lib/src/link/link.component.html, src/lib/src/link/link.component.ts, src/lib/src/login-form/login-form.component.html
Currently hacking a negative tab index on parent components. Feels hacky.
=> fix(log-in): correct tabindex flow

package.json, src/demo/src/app/components/input.component.ts, src/demo/src/app/components/search.component.ts, src/demo/yarn.lock, src/lib/src/input/input.component.html, src/lib/src/input/input.component.spec.ts, src/lib/src/input/input.component.ts, src/lib/src/search/search.component.html, src/lib/src/search/search.component.ts
Also allow search component to pass the autofocus value down to the input.
Also fix issue with the lint commit hook when a spec file is changed.
=> feat(Input): support autofocus on component load

src/demo/src/app/components/navigation.component.ts, src/lib/src/navigation/navigation.component.html, src/lib/src/navigation/navigation.component.scss, src/lib/src/navigation/navigation.component.spec.ts, src/lib/src/navigation/navigation.component.ts, src/lib/src/navigation/navigation.module.ts, src/lib/src/utilities/groupBy.ts, src/lib/src/utilities/interfaces/navigation-item.interface.ts, src/lib/src/utilities/interfaces/navigation-payload.interface.ts, yarn.lock
- using real links rather than buttons
- support for router links and external links
- support for active route styles closes #261
=> feat(navigation): now supports router links, external links and active styles

package.json
=> chore(package): update karma-coverage-istanbul-reporter to version 1.3.3

package.json
=> chore(package): update gulp-sourcemaps to version 2.6.3

src/lib/src/radio-group/radio-group.component.scss, src/lib/src/scss/helpers/_typography.scss
- Radio button weight updated
- Base body type is 300 weight
- Body type 2 is 400 weight
- Radio options have vertical spacing now
=> Radio font weight

src/demo/src/app/app.module.ts, src/lib/src/select/select.component.scss
Recent layout changes affected the paginator incorrectly.
=> fix(Select): layout fix for select when inside paginator

src/demo/src/app/components/checkbox/checkbox.component.ts, src/demo/src/app/components/date-range/date-range.component.html, src/demo/src/app/components/datepicker/datepicker.component.html, src/demo/src/app/components/input/input.component.html, src/demo/src/app/components/menu/menu.component.ts, src/demo/src/app/components/select/select.component.html, src/demo/src/styles.scss, src/lib/src/copy/copy.component.scss, src/lib/src/copy/copy.component.ts, src/lib/src/date-range/date-range.component.html, src/lib/src/date-range/date-range.component.ts, src/lib/src/datepicker/datepicker.component.html, src/lib/src/datepicker/datepicker.component.scss, src/lib/src/datepicker/datepicker.component.ts, src/lib/src/input/input.component.html, src/lib/src/input/input.component.ts, src/lib/src/link/link.component.scss, src/lib/src/scss/global/terminus-ui.scss, src/lib/src/search/search.component.html, src/lib/src/select/select.component.html
- all components respect theme. fixes #554 
- move core theme creation to ui library
=> fix: all components respecting theme, move angular core theme into library

src/demo/src/app/components/table/table.component.html, src/lib/src/table/table.component.scss
=> fix(Table): table now fills ts-card components fully

src/lib/src/scss/helpers/_typography.scss
=> fix(SCSS): update typography styles to match imported roboto weights

package.json, src/demo/src/app/components/card/card.component.html, src/lib/setupJest.ts, src/lib/src/card/card-title.directive.spec.ts, src/lib/src/card/card-title.directive.ts, src/lib/src/card/card.component.md, src/lib/src/card/card.component.scss, src/lib/src/card/card.module.ts, src/lib/src/pipes/time-ago/time-ago.pipe.ts, src/lib/src/sort/sort.directive.spec.ts, src/lib/tsconfig.spec.json, yarn.lock
=> feat(Card): Add directive for card titles

src/lib/src/card/card.component.html, src/lib/src/card/card.component.scss, src/lib/src/scss/helpers/_card.scss
BREAKING CHANGE:
Now depending on ngx-tools as peer dependency. \`yarn add @terminus/ngx-tools --exact\`
ISSUES CLOSED: #640, #636
=> fix(Card): fix card layout bug for linkedin wizard

README.md, src/demo/src/app/components/checkbox/checkbox.component.html, src/demo/src/app/components/checkbox/checkbox.component.ts, src/lib/src/checkbox/checkbox.component.html, src/lib/src/checkbox/checkbox.component.md, src/lib/src/checkbox/checkbox.component.spec.ts, src/lib/src/checkbox/checkbox.component.ts
=> 632 checkbox is selected bug

src/lib/src/button/button.component.spec.ts, src/lib/src/button/button.component.ts, src/lib/src/card/card-title.directive.ts, src/lib/src/sort/sort-header.component.ts, src/lib/src/sort/sort.directive.ts, src/lib/src/spacing/vertical-spacing.directive.ts
=> chore: Only throw errors in dev mode

package.json, src/lib/index.ts, src/lib/src/utilities/version/version.spec.ts, src/lib/src/utilities/version/version.ts, tooling/ci/inject-version.sh, yarn.lock
=> fix(CI): expose version number

src/demo/src/app/components/radio/radio.component.html, src/demo/src/app/components/radio/radio.component.ts, src/lib/src/radio-group/radio-group.component.html, src/lib/src/radio-group/radio-group.component.md, src/lib/src/radio-group/radio-group.component.spec.ts, src/lib/src/radio-group/radio-group.component.ts, src/lib/src/radio-group/radio-group.module.ts, src/lib/src/utilities/interfaces/radio-option.interface.ts
- Fix incorrect type in `TsRadioOption` interface
- Expose `TsRadioChange` event
- Fix for default selections not being set - closes #678 
- Clarity updates for docs and demo
=> 678 radio default selection

docs/components/TsInputComponent.html, docs/coverage.html, src/demo/src/app/components/input/input.component.html, src/lib/src/input/input.component.spec.ts, src/lib/src/input/input.component.ts
- now using `onPush` change detection
- exporting as `tsInput`
ISSUES CLOSED: #689
=> fix(Input): now using onpush change detection

src/demo/src/app/components/datepicker/datepicker.component.html, src/demo/src/app/components/input/input.component.ts, src/lib/src/datepicker/datepicker.component.html, src/lib/src/datepicker/datepicker.component.ts
=> fix(Datepicker): now supports a hint like a TsInput

package.json, src/lib/src/autocomplete/autocomplete.component.spec.ts, src/lib/src/autocomplete/autocomplete.component.ts, src/lib/src/pipes/date/date.pipe.spec.ts, src/lib/src/services/validators/validators/equalToControl/equalToControl.spec.ts, src/lib/src/sort/sort.directive.ts, src/lib/src/sort/sort.spec.ts, src/lib/tsconfig.spec.json, yarn.lock
- Update Jest lib
- Update jest angular preset
- Fix TS errors in tests now exposed by updates
- Enabled experimental decorators in `tsconfig.spec` to silence warnings
=> Update jest preset

LICENSE
=> docs: update company name

terminus-ui/src/scss/helpers/_typography.scss
=> fix(Select): fix alignment of select and input

terminus-ui/src/select/select.component.spec.ts, terminus-ui/src/select/select.component.ts
=> refactor(Select): now provides helpful error message when used incorrectly

package.json, yarn.lock
=> fix(CI): generate changelog

README.md
=> chore: readme now links to source directories, fix incorrect directive links

terminus-ui/src/paginator/paginator.component.spec.ts, terminus-ui/src/paginator/paginator.component.ts
=> fix(Paginator): fix for zero-based page bug

package.json
According to what I've read, publishConfig is set correctly.
=> fix(CI): another try at releasing on next

terminus-ui/package.json
=> fix(CI): publish @next

demo/app/components/copy/copy.component.ts, terminus-ui/src/copy/copy.component.html, terminus-ui/src/copy/copy.component.scss, terminus-ui/src/copy/copy.module.ts
Also a fix for the inconsistent padding around the icon.
ISSUES CLOSED: #369
=> fix(Copy): quick copy button has tooltip, fix layout bug

demo/app/components/toggle/toggle.component.html, terminus-ui/src/toggle/toggle.component.spec.ts, terminus-ui/src/toggle/toggle.component.ts
=> fix(Toggle): now supports setting checked value via input

demo/app/components/radio/radio.component.html, terminus-ui/src/radio-group/radio-group.component.html, terminus-ui/src/radio-group/radio-group.component.scss, terminus-ui/src/radio-group/radio-group.component.ts
=> feat(RadioGroup): support for short version in visual mode

demo/app/components/checkbox/checkbox.component.ts, terminus-ui/src/checkbox/checkbox.component.html, terminus-ui/src/checkbox/checkbox.component.spec.ts, terminus-ui/src/checkbox/checkbox.component.ts
=> fix(Checkbox): isChecked input now working

demo/app/components/radio/radio.component.html, demo/app/components/radio/radio.component.ts, terminus-ui/src/radio-group/radio-group.component.html, terminus-ui/src/radio-group/radio-group.component.scss
- Visual mode supports sublabels
- Fixed legend display bug from Bootsrap
- Fix checkmark display bug
=> 956 radio visual sublabel

terminus-ui/src/radio-group/radio-group.component.spec.ts, terminus-ui/src/radio-group/radio-group.component.ts
=> fix(RadioGroup): small option true/false reflects DOM visual

terminus-ui/src/icon/icon.component.scss
=> fix(Icon): button vertical alignment now correct

demo/app/components/csv-entry/csv-entry.component.html, terminus-ui/src/csv-entry/csv-entry.component.html, terminus-ui/src/csv-entry/csv-entry.component.md, terminus-ui/src/csv-entry/csv-entry.component.spec.ts, terminus-ui/src/csv-entry/csv-entry.component.ts
=> feat(CSVEntry): static header cell content can be passed in

demo/app/app.module.ts, demo/app/components/chart2/chart2.component.html, demo/app/components/chart2/chart2.component.ts, demo/app/components/components.constant.ts, jest.config.js, package.json, terminus-ui/package.json, terminus-ui/src/chart2/amcharts.service.ts, terminus-ui/src/chart2/chart2.component.html, terminus-ui/src/chart2/chart2.component.md, terminus-ui/src/chart2/chart2.component.scss, terminus-ui/src/chart2/chart2.component.ts, terminus-ui/src/chart2/chart2.module.ts, terminus-ui/src/index.ts, terminus-ui/src/module.ts, tooling/cz-config.js, tsconfig.json, yarn.lock
Currently unable to test with jest due to how the library is imported.
Since this is only a proof of concept, I have disabled test coverage reporting for `chart2`.
=> feat(Chart2): amCharts working

terminus-ui/src/validation-messages/validation-messages.component.scss
=> fix(RadioGroup): required validation now displays correctly in visual mode

terminus-ui/src/button/button.component.scss
=> fix(Button): update radius to 3px to match other UI elements

demo/app/components/card/card.component.html, terminus-ui/src/card/card.component.html, terminus-ui/src/card/card.component.scss, terminus-ui/src/card/card.component.ts
=> fix(Card): support flat card style

demo/app/components/icon/icon.component.html, terminus-ui/src/icon/icon.component.scss, terminus-ui/src/icon/icon.component.spec.ts, terminus-ui/src/icon/icon.component.ts
=> feat(Icon): now supports a version with background

demo/app/components/select/select.component.html, demo/app/components/select/select.component.ts, terminus-ui/src/select/select.component.spec.ts, terminus-ui/src/select/select.component.ts
=> fix(Select): trigger change detection when the formControl changes

terminus-ui/src/card/card.component.scss
This will allow consumers to dynamically change the height with a transition
ISSUES CLOSED: #1028
=> fix(Card): add transition to height

demo/app/components/validation/validation.component.html, terminus-ui/package.json, terminus-ui/src/input/input.component.md, terminus-ui/src/input/input.component.ts
- fix for incorrect validation timing (datepicker)
- fix for docs
- updates for demos
=> Hotfix input datepicker bug

terminus-ui/src/autocomplete/autocomplete.component.ts
Should fix array mutation
ISSUES CLOSED: #1065
=> fix(Autocomplete): now also slicing before seeding the form control

terminus-ui/src/checkbox/checkbox.component.spec.ts, terminus-ui/src/checkbox/checkbox.component.ts, terminus-ui/src/file-upload/file-upload.component.ts, terminus-ui/src/input/input.component.ts, terminus-ui/src/radio-group/radio-group.component.spec.ts, terminus-ui/src/radio-group/radio-group.component.ts, terminus-ui/src/search/search.component.ts, terminus-ui/src/select/select.component.spec.ts, terminus-ui/src/select/select.component.ts, terminus-ui/src/toggle/toggle.component.spec.ts, terminus-ui/src/toggle/toggle.component.ts, terminus-ui/src/utilities/cva-provider-factory/cva-provider-factory.spec.ts, terminus-ui/src/utilities/cva-provider-factory/cva-provider-factory.ts
Abstracting the logic out will keep code and specs more DRY
ISSUES CLOSED: #1068
=> refactor: abstract custom CVA provider to factory

terminus-ui/src/file-upload/file-upload.component.spec.ts, terminus-ui/src/file-upload/file-upload.module.ts, terminus-ui/src/file-upload/mime-types.ts
- support gif uploads
- expose TsSelectedFile class
=> 1082 file upload tweaks

terminus-ui/src/input/input.module.ts, yarn.lock
This should allow lazy loaded routes to work
ISSUES CLOSED: #1083
=> fix(Input): no longer importing from platform browser

tslint.json
=> chore: TSLint updated not to report on long urls

terminus-ui/src/csv-entry/csv-entry.component.spec.ts, terminus-ui/src/csv-entry/csv-entry.component.ts
TSV is the default
closes #1076
=> feat(CSVEntry): CSV output can be either CSV or TSV

demo/app/components/input/input.component.html, terminus-ui/src/input/input.component.scss
=> fix(TsInput): Add margin bottom to all ts input elements

terminus-ui/src/tooltip/tooltip.component.spec.ts, terminus-ui/src/tooltip/tooltip.component.ts
deprecating 'left' and 'right'
ISSUES CLOSED: #1114
=> chore(Tooltip): added deprecation warning for tooltip position

terminus-ui/src/card/card.component.scss
=> fix(Card): overlay bleeds to edges on a table in a card

terminus-ui/src/csv-entry/csv-entry.component.spec.ts, terminus-ui/src/csv-entry/csv-entry.component.ts, terminus-ui/src/utilities/strip-control-characters/stripControlCharacters.spec.ts, terminus-ui/src/utilities/strip-control-characters/stripControlCharacters.ts
=> fix(CSVEntry): correctly stripping control characters out of pasted content

demo/app/components/file-upload/file-upload.component.ts, terminus-ui/src/file-upload/file-upload.component.spec.ts, terminus-ui/src/file-upload/mime-types.ts, terminus-ui/src/file-upload/selected-file.spec.ts, terminus-ui/src/file-upload/selected-file.ts
=> feat(FileUpload): MP4 upload support

demo/app/app.module.ts, terminus-ui/src/input/date-adapter.ts
=> fix: aoT build bug fixes

README.md, demo/app/components/input/input.component.html, demo/app/components/input/input.component.ts, terminus-ui/src/input/input.component.html, terminus-ui/src/input/input.component.md, terminus-ui/src/input/input.component.spec.ts, terminus-ui/src/input/input.component.ts, terminus-ui/src/input/testing/test-components.ts
=> feat(Input): textarea support

demo/app/components/scrollbars/scrollbars.component.html, demo/app/components/scrollbars/scrollbars.component.ts, terminus-ui/src/scrollbars/scrollbars.component.md, terminus-ui/src/scrollbars/scrollbars.component.ts
=> docs(Scrollbars): add usage docs for scroll methods

terminus-ui/src/checkbox/checkbox.component.html, terminus-ui/src/checkbox/checkbox.component.spec.ts, terminus-ui/src/checkbox/checkbox.component.ts
=> test(Checkbox): update tests to catch missed path

demo/app/components/select/select.component.html, demo/app/components/select/select.component.ts, terminus-ui/src/select/select.component.html, terminus-ui/src/select/select.component.scss, terminus-ui/src/select/select.component.spec.ts, terminus-ui/src/select/select.component.ts, terminus-ui/src/select/testing/test-components.ts, terminus-ui/src/select/testing/test-helpers.ts
Add the ability to filter options from a select list by adding a filter input.
=> Add filter capability

.gitignore, terminus-ui/src/confirmation/confirmation.directive.spec.ts, terminus-ui/src/validation-messages/validation-message.service.spec.ts, terminus-ui/src/validation-messages/validation-message.service.ts
=> fix(DateRange): formatting of error message is now correct

terminus-ui/src/login-form/login-form.component.html
=> fix(LoginForm): input margins are equalized

terminus-ui/src/checkbox/checkbox.component.scss
ISSUES CLOSED: #1155 
Some mat-menu styles were removed when writing select menu styles
=> fix(Checkbox): padding fixed for checkbox within material menu

demo/app/components/validation/validation.component.html, demo/app/components/validation/validation.component.ts, terminus-ui/src/validation-messages/validation-message.service.ts, terminus-ui/src/validators/validators.service.md, terminus-ui/src/validators/validators.service.mock.ts, terminus-ui/src/validators/validators.service.spec.ts, terminus-ui/src/validators/validators.service.ts, terminus-ui/src/validators/validators/isInRange/isInRange.spec.ts, terminus-ui/src/validators/validators/isInRange/isInRange.ts
=> feat(Validators): isInRange Validator available in 9.x

demo/app/components/validation/validation.component.html, demo/app/components/validation/validation.component.ts, package.json, terminus-ui/src/validation-messages/validation-message.service.ts, terminus-ui/src/validators/validators.service.md, terminus-ui/src/validators/validators.service.mock.ts, terminus-ui/src/validators/validators.service.spec.ts, terminus-ui/src/validators/validators.service.ts, terminus-ui/src/validators/validators/isInRange/isInRange.spec.ts, terminus-ui/src/validators/validators/isInRange/isInRange.ts, yarn.lock
package.json dependency on terminus-ui was also updated to pick up the latest version
ISSUES CLOSED: #1210
=> chore(Validators): isInRange and inCollection added to 10.x

CONTRIBUTING.md
also minor edit for clarity
ISSUES CLOSED: #1220
=> fix: docs: links are all correct

demo/app/components/confirmation/confirmation.component.html, demo/app/components/confirmation/confirmation.component.ts, terminus-ui/src/confirmation/confirmation-modal.component.html, terminus-ui/src/confirmation/confirmation-modal.component.scss, terminus-ui/src/confirmation/confirmation-modal.component.ts, terminus-ui/src/confirmation/confirmation.directive.spec.ts, terminus-ui/src/confirmation/confirmation.directive.ts
This also covers ticket 1188, adding customizable confirm and cancel button text, and allowing for custom explanation text within the confirmation modal.
=> 1203 10x confirmation escape

demo/app/components/csv-entry/csv-entry.component.html, demo/app/components/csv-entry/csv-entry.component.ts, terminus-ui/src/csv-entry/csv-entry.component.md, terminus-ui/src/csv-entry/csv-entry.component.scss, terminus-ui/src/csv-entry/csv-entry.component.spec.ts, terminus-ui/src/csv-entry/csv-entry.component.ts
=> feat(CSVEntry): fullwidth option is now available

README.md, terminus-ui/src/csv-entry/csv-entry.component.md, terminus-ui/src/csv-entry/csv-entry.component.spec.ts, terminus-ui/src/csv-entry/csv-entry.component.ts
BREAKING CHANGE:
Default output format is now CSV (was TSV)
ISSUES CLOSED: #1120
=> feat(CSVEntry): default output is now CSV

demo/app/components/csv-entry/csv-entry.component.html, terminus-ui/src/csv-entry/csv-entry.component.scss, terminus-ui/src/csv-entry/csv-entry.component.ts
=> fix(CSVEntry): fullwidth works within flex layout = row

terminus-ui/src/select/select.component.ts
=> fix(Select): fix for array mutation

terminus-ui/src/input/input.component.spec.ts, terminus-ui/src/input/input.component.ts, terminus-ui/src/input/testing/test-components.ts
=> fix(Input): Add a check to ensure not to try to run change detection

.github/CODEOWNERS
=> chore: add Shani and Wendy as code owners

terminus-ui/src/confirmation/confirmation.directive.ts
=> fix(Confirmation): escape key dismisses modal in 9.x

terminus-ui/utilities/src/strip-control-characters/strip-control-characters.ts
Using this to trigger a release
=> fix(Utilities): fixed incorrect docs

demo/app/components/select/select.component.html, demo/app/components/select/select.component.ts, terminus-ui/src/select/select.component.html, terminus-ui/src/select/select.component.spec.ts, terminus-ui/src/select/select.component.ts, terminus-ui/src/select/testing/test-components.ts, terminus-ui/src/select/testing/test-helpers.ts
=> fix(Select): Use formatUIFn function input for seeding autocomplete values

README.md, terminus-ui/validators/src/validators.service.md
- removed validators that no longer exist
- add validators that were missing
ISSUES CLOSED: #1301
=> chore(Validators): update list of available validators

DEVELOPMENT.md
=> chore: update development docs to explain usage docs generation

terminus-ui/src/select/select.component.spec.ts, terminus-ui/src/select/select.component.ts
=> fix(Select): autocomplete single selection mode modifying the passing object and not displaying selection correctly

demo/app/components/select/select.component.html, demo/app/components/select/select.component.ts, terminus-ui/menu/package.json, terminus-ui/select/src/select.component.html, terminus-ui/select/src/select.component.spec.ts, terminus-ui/select/src/select.component.ts, terminus-ui/select/testing/src/test-components.ts, terminus-ui/select/testing/src/test-helpers.ts
=> fix(Select): v10 bug fixes moved to master

terminus-ui/checkbox/src/checkbox.component.scss
=> fix(Select): checkbox text within select no longer being truncated

terminus-ui/navigation/src/navigation.component.md, terminus-ui/table/src/table.component.md
update to table component's usage doc's table of content
ISSUES CLOSED: #1313
=> chore(Navigation): usage docs now available

tooling/ci/build-demos-aot.sh
=> chore(Demo): updated incorrect base href

terminus-ui/tsconfig.compodoc.json
=> fix(CI): docs now correctly generated

.circleci/config.yml, tooling/ci/build-demos-aot.sh, tooling/ci/demos-deploy.sh
=> chore(Demo): now publishing to github pages for v8

terminus-ui/date-range/src/date-range.component.ts, terminus-ui/input/src/input.component.spec.ts, terminus-ui/input/src/input.component.ts
=> fix(daterange): on initial load, date range isn't getting value and status set properly

terminus-ui/select/src/select.component.html, terminus-ui/select/src/select.component.ts
=> fix(Select): panel no longer spills outside of viewport

demo/app/components/select/select.component.html, demo/app/components/select/select.component.ts, terminus-ui/select/src/select.component.html, terminus-ui/select/src/select.component.scss, terminus-ui/select/src/select.component.ts
- max-height was not being set via CSS
- panel positioning no longer changes via scroll
- dynamic panel positioning no longer set
=> fix(Select): correct max height & disable panel positioning

terminus-ui/csv-entry/src/csv-entry.component.spec.ts, terminus-ui/csv-entry/src/csv-entry.component.ts
=> fix(CsvEntry): when reset, reset to customized column number and remove all errors

terminus-ui/select/src/select.component.spec.ts, terminus-ui/select/src/select.component.ts, terminus-ui/select/testing/src/test-components.ts, terminus-ui/select/testing/src/test-helpers.ts
=> fix(Select): show required validation message when it's required and not filled on blur

demo/app/components/select/select.component.html, demo/app/components/select/select.component.ts, terminus-ui/checkbox/src/checkbox.component.scss, terminus-ui/select/src/optgroup/optgroup.component.scss, terminus-ui/select/src/option/option.component.scss, terminus-ui/select/src/select-animations.ts, terminus-ui/select/src/select.component.html, terminus-ui/select/src/select.component.scss, terminus-ui/select/src/select.component.ts
- Fix horizontal panel position for checkbox and optgroup selects
- Re-enable panel opening up
- Fix issue where panel opens upwards too far away from select
- Selected option should be vertically centered over select
=> 1351 select positioning bugs

terminus-ui/input/src/input.component.spec.ts, terminus-ui/input/src/input.component.ts
ISSUES CLOSED: #1167 
Note: There is still an outstanding mask issue with percentages: https://github.com/GetTerminus/terminus-ui/issues/1371
=> fix(Input): sanitized mask value no longer overwriting UI

README.md, demo/app/components/validation/validation.component.html, demo/app/components/validation/validation.component.ts, package.json, terminus-ui/validation-messages/src/validation-messages.service.ts, terminus-ui/validators/src/validators.service.md, terminus-ui/validators/src/validators.service.ts, terminus-ui/validators/src/validators/domain/domain.spec.ts, terminus-ui/validators/src/validators/domain/domain.ts, yarn.lock
=> feat(Validation): add domain validator

terminus-ui/file-upload/src/file-upload.component.ts
=> fix(FileUpload): protect against cdr being called after it's destroyed

terminus-ui/file-upload/src/file-upload.module.ts, terminus-ui/input/src/input.component.ts, terminus-ui/input/src/input.module.ts, terminus-ui/pipes/src/date/date.pipe.spec.ts, terminus-ui/pipes/src/date/date.pipe.ts, terminus-ui/validation-messages/src/validation-messages.module.ts, terminus-ui/validation-messages/src/validation-messages.service.ts, terminus-ui/validation-messages/src/validation-messages.services.spec.ts
=> feat(Validation): use date pipe

terminus-ui/input/src/input.component.scss
=> fix(DatePicker): overwrite material z-index with our map

terminus-ui/card/src/card.component.spec.ts
=> chore(Card): convert card component to integration test

package.json, yarn.lock
Using local version did not work on CI
=> revert(Packages): remove yarn

README.md, demo/app/components/pipes/pipes.component.html, terminus-ui/navigation/src/navigation.component.html, terminus-ui/navigation/src/navigation.component.spec.ts, terminus-ui/navigation/src/navigation.component.ts, terminus-ui/navigation/src/navigation.module.ts, terminus-ui/pipes/src/pipes.module.ts, terminus-ui/pipes/src/sentence-case/sentence-case.pipe.spec.ts, terminus-ui/pipes/src/truncate/truncate.pipe.spec.ts, terminus-ui/pipes/src/truncate/truncate.pipe.ts
=> feat(Pipes): truncate pipe is available

terminus-ui/table/src/table.component.spec.ts
=> test(Table): added missing test for incorrect param

terminus-ui/confirmation/src/confirmation.directive.ts
=> fix(Confirmation): background will not scroll away from overlay

terminus-ui/confirmation/src/confirmation-overlay.component.scss
=> fix(Confirmation): button does not move when overlay opens

terminus-ui/select/src/select.component.html
=> fix(Select): updated filter label text

terminus-ui/link/src/link.component.html, terminus-ui/link/src/link.component.spec.ts
=> chore(Link): tests converted to integration

terminus-ui/icon-button/src/icon-button.component.spec.ts, terminus-ui/icon-button/src/icon-button.component.ts
=> chore(IconButton): now with integration tests

terminus-ui/select/src/select.component.html, terminus-ui/select/src/select.component.spec.ts
=> fix(Select): space character works in autocomplete

.github/bug.md, .github/feature.md
=> chore(community): bug.md and feature.md are now available

terminus-ui/card/src/card.component.spec.ts
=> chore(Card): 100% test coverage

terminus-ui/input/src/input.component.scss, terminus-ui/loading-overlay/src/loading-overlay.component.scss, terminus-ui/scss/docs/z-index.md, terminus-ui/scss/helpers/_triangle.scss, terminus-ui/scss/helpers/_z-index.scss, terminus-ui/select/src/option/option.component.scss, terminus-ui/validation-messages/src/validation-messages.component.scss
💥 BREAKING CHANGE 💥 
change header, menu, panel-overlay, and overlay
ISSUES CLOSED: #1377
Update the following z-index values:
| before             | after                      |
| -------------- | ----------------------- |
| header            | global-header                 |
| overlay            | global-overlay                |
| panel-overlay | attached-panel-overlay |
| menu               | attached-panel-overlay |
=> chore(SCSS): *BREAKING CHANGE* z-index name and order updated for clarity
