GetTerminus/terminus-ui

README.md

Github and NPM had different published versions

fix(CI): still trying for 0.2.6

---

src/demo/src/app/components/menu.component.ts
src/lib/src/button/button.component.scss
src/lib/src/menu/menu.component.html
src/lib/src/menu/menu.component.scss

https://www.pivotaltracker.com/story/show/151170044
The material menu component has no native support for disabled. And because they are attaching the click handler to the custom `ts-button` component, it breaks the native HTML disabled ability for buttons.
Hacking a solution using `pointer-events: none`.

Block UI interaction when menu is disabled

---

src/lib/src/button/button.component.scss
src/lib/src/input/input.component.ts
src/lib/src/utilities/reactive-form-base.component.ts

Changes:
4d2ae59 (Benjamin Charity, 11 seconds ago)
fix(button): ripple no longer spills outside of collapsible buttons
2ecf715 (Benjamin Charity, 42 seconds ago)
chore(input): explicitly define the form control type

Fix ripple spilling out of collapsible buttons

---

src/lib/src/button/button.component.spec.ts
src/lib/src/button/button.component.ts
src/lib/src/copy/copy.component.spec.ts
src/lib/src/copy/copy.component.ts
src/lib/src/date-range/date-range.component.ts
src/lib/src/loading-overlay/loading-overlay.directive.spec.ts
src/lib/src/login-form/login-form.component.ts
src/lib/src/services/document/document.service.mock.ts
src/lib/src/services/window/window.service.mock.ts
tslint.json

- remove outdated tslint rules
- collapsable buttons no longer cause error during quick navigation

fix(Button): Correctly handling timeouts when the component is destroyed

---

package.json
src/lib/jestGlobalMocks.ts
src/lib/setupJest.ts
src/lib/src/input/input.component.spec.ts
src/lib/src/login-form/login-form.component.spec.ts
tooling/ci/test-unit.sh
yarn.lock

NOTE: branch coverage is very different (lower). Something to do with
@Input’s being ‘branches’ now. Can’t find any info on it yet.

chore(CI): Jest tests now working

---

src/lib/src/pipes/date/date.pipe.spec.ts
src/lib/src/pipes/date/date.pipe.ts
src/lib/src/pipes/time-ago/time-ago.pipe.spec.ts
src/lib/src/pipes/time-ago/time-ago.pipe.ts

- Update date formats. Fixes: #598 
- Handle `null|''` values correctly. Fixes: #586

589 date pipe tweaks

---

src/demo/src/app/app.module.ts
src/lib/index.ts
src/lib/src/module.ts
src/lib/src/pipes/pipes.module.ts

CLI doesn’t seem to be tree-shaking the UI library. This fixes the issue when Pipes are not included to a module.

fix(Pipes): Fix for AoT build

---

src/demo/src/app/components/card/card.component.html
src/lib/src/card/card.component.html
src/lib/src/card/card.component.scss
src/lib/src/card/card.component.ts

- card text no longer overlaps the disabled icon or utility menu if no title directive if used
- when disabled, a card's utility menu is now disabled also

708 709 card tweaks

---

src/lib/src/link/link.component.spec.ts
src/lib/src/link/link.component.ts
src/lib/src/services/document/document.service.spec.ts
src/lib/src/services/window/window.service.spec.ts

Also added spies for window/document services so that console.log isn’t actually called during tests

chore(Link): add deprecation notice for [color] param

---

src/demo/src/app/components/tooltip/tooltip.component.ts
src/lib/src/tooltip/tooltip.component.html
src/lib/src/tooltip/tooltip.component.scss
src/lib/src/tooltip/tooltip.component.ts

Provide an input to tooltip component named `hasUnderline`.
If it's true, dotted underline showing underneath the text.
It's default to false.

feat(Tooltip): Create tooltip extension that adds a dotted underline

---

src/lib/src/services/validation-message/validation-message.service.spec.ts
src/lib/src/services/validation-message/validation-message.service.ts

Correct that validation message references a wrong key.

fix(Validator): Hotfix incorrect validation message

---

terminus-ui/src/loading-overlay/loading-overlay.component.scss
terminus-ui/src/scss/helpers/_z-index.scss

This allows in-page overlays to be below items like the header while still allowing a full page overlay to cover all content.
ISSUES CLOSED: #850

fix(LoadingOverlay): add another zindex level for internal overlays

---

terminus-ui/src/autocomplete/autocomplete.component.html

fix(Autocomplete): clicking the x on a chip now correctly removes the option

---

terminus-ui/src/file-upload/selected-file.spec.ts
terminus-ui/src/file-upload/selected-file.ts

Previously, only images would trigger the FileReader to seed it's contents
ISSUES CLOSED: #991

fix(FileUpload): fileContents now available for files that are not images

---

terminus-ui/src/scrollbars/scrollbars.component.ts

Can't construct a query for the property "scrollbars" of "ScrollbarsComponent" since the query
selector wasn't defined.

fix(Scrollbars): use forward ref to fix demo issue

---

package.json
terminus-ui/src/input/input.component.spec.ts
terminus-ui/src/input/input.component.ts
yarn.lock

Add a check to ensure that not to try to run change detection on a destroyed view.
close #1095

fix(TsInput): Add a check to ensure not to try to run change detection

---

demo/app/components/autocomplete/autocomplete.component.html
terminus-ui/src/autocomplete/autocomplete.component.ts

1) removing `[multiple]="comparator"` 
2) typeahead and select one
3) remove that one and try to typeahead and select another one
4) that’s when this error message shows up.

fix(Autocomplete): correctly allows removal when in single select mode

---

demo/app/components/date-range/date-range.component.html
demo/app/components/date-range/date-range.component.ts
terminus-ui/src/date-range/date-range.component.html
terminus-ui/src/date-range/date-range.component.spec.ts
terminus-ui/src/date-range/date-range.component.ts
terminus-ui/src/date-range/testing/test-components.ts
terminus-ui/src/date-range/testing/test-helpers.ts
terminus-ui/src/form-field/form-field-control.ts
terminus-ui/src/form-field/form-field.component.html
terminus-ui/src/input/date-adapter.ts
terminus-ui/src/select/select.component.ts
terminus-ui/src/validation-messages/validation-messages.component.spec.ts
terminus-ui/src/validation-messages/validation-messages.component.ts

- Now using an internal FormControl to sync changes and values between the date range component and the passed in FormGroup.
- Rewritten tests to use `TestBed` rather than `new Class`
- FormField now works with injected ngControl or formControl property
- Validation messages component now triggers change detection when the passed in control's status changes.
- Added `isFilterable` to select docs since it was missed during the docs addition.

DateRange: Validation now correct

---

README.md
terminus-ui/package.json

BREAKING CHANGE:
Material is now a peer dependency so it must be installed by the consumer. This is so a consumer can use parts of Material outside of the library if needed.
ISSUES CLOSED: #1091

refactor(Packages): moved Material to a peer dependency

---

terminus-ui/pipes/src/time-ago/time-ago.pipe.ts

Apparently they didn't have time to update their docs

fix(Pipes): fix for date-fns api change

---

.circleci/config.yml
tooling/ci/rename-typings-index.sh

This should fix an issue when importing from the top level and building aot

chore(CI): rename primary typings file

---

terminus-ui/input/src/input.component.md

ISSUES CLOSED: #1214
@shani-terminus I traced down the same path you did and got the same results. I looked deeper into how `ngModel` works and it seems that it doesn't actually care about the `required` attribute that is added to the underlying input element. Rather, it is looking for the `required` attribute that lives on whichever element is the ControlValueAccessor. So in our case, if the user adds a standard `required` attribute to a `ts-input`, then `ngModel` validation works (ie shows error messages).
```
// works:
<ts-input required></ts-input>
```
After some testing it seems that we cannot mirror the `isDisabled` flag to set the input as required. I tried setting it via the `host` definition, via the template and via the `Renderer2` with no luck. Each method correctly sets the …

docs(Input): update docs to clarify how to acheive validation using ngModel

---

demo/app/components/date-range/date-range.component.ts
terminus-ui/date-range/src/date-range.component.html
terminus-ui/date-range/src/date-range.component.md
terminus-ui/date-range/src/date-range.component.spec.ts
terminus-ui/date-range/src/date-range.component.ts
terminus-ui/date-range/testing/src/test-helpers.ts

ISSUES CLOSED: #1359
- fix bug where range wasn't emitted when an input was cleared manually
- created some more test helpers
- cleaned up tests using new helpers
- added test helpers to usage doc
- updated demo to use current date
- added helper classes to make it easier to query a specific input

fix(DateRange): now emits change when an input is manually cleared

---

package.json
terminus-ui/form-field/src/form-field.component.scss
terminus-ui/input/src/input.component.scss
terminus-ui/input/src/input.component.ts

ISSUES CLOSED: #1336 
- added scoping class for datepicker instances of input
- datepicker icon focus state is now correctly centered

fix(Input): datepicker icon focus state now centered correctly

---

terminus-ui/select/src/select.component.spec.ts
terminus-ui/select/testing/src/test-helpers.ts
terminus-ui/validation-messages/testing/package.json
terminus-ui/validation-messages/testing/src/public-api.ts
terminus-ui/validation-messages/testing/src/test-helpers.ts

Note: Once I was digging into this issue I realized that the validation messages helper(s) should live with their own module rather than at a top level.
ISSUES CLOSED: #1355

refactor: move validation messages test helper into correct module

---

package.json
terminus-ui/package.json
yarn.lock

ngx-tools has a breaking change that just released v6. We don't need to force v6 usage for the UI library so we will support anything greater than v5 for now.

fix(Packages): allow v5 or v6 to be used for ngx-tools

---

terminus-ui/checkbox/src/checkbox.component.md
terminus-ui/checkbox/testing/package.json
terminus-ui/checkbox/testing/src/public-api.ts
terminus-ui/checkbox/testing/src/test-helpers.ts
terminus-ui/date-range/src/date-range.component.spec.ts
terminus-ui/date-range/testing/src/test-helpers.ts
terminus-ui/input/src/input.component.html
terminus-ui/input/src/input.component.md
terminus-ui/input/src/input.component.spec.ts
terminus-ui/input/testing/src/test-helpers.ts
terminus-ui/radio-group/src/radio-group.component.html
terminus-ui/radio-group/src/radio-group.component.md
terminus-ui/radio-group/src/radio-group.component.ts
terminus-ui/radio-group/testing/package.json
terminus-ui/radio-group/testing/src/public-api.ts
terminus-ui/radio-group/testing/src/test-helpers.ts
terminus-ui/select/src/select.component.md
terminus-ui/select/src/select.component.spec.ts
terminus-ui/select/testing/src/test-components.ts
terminus-ui/select/testing/src/test-helpers.ts

ISSUES CLOSED: #1074 
- Moved test helpers from core into library
- Added JSDoc comments to all helpers
- Added all helpers to the primary component readmes
- Added a couple classes for easier targeting
- Removed unneeded import
- Remove unneeded ID setter
---
`toggleCheckbox` replaces `checkTsCheckbox` and `uncheckTsCheckbox`
`sendInput` replaces `setTsInputValue` and `setTsDatePicker`
`selectStandardRadio`/`selectVisualRadio` replaces `setTsRadioBoxValueByText`
`setDateRangeValues` replaces `setTsDateRangeValue`
`getAllOptionInstances` replaces `getOptions`
`openSelect` replaces `openSelector`
`selectOption` replaces `selectOption`

fix(TestHelpers): moved all core test helpers into the library

---

.circleci/config.yml
package.json
yarn.lock

- add yarn in the hopes it's cached for the next PR (coming next)
- ensure CI is installing without adjusting the lockfile

1384 add yarn

---

CHANGELOG.md

To help kickstart the changelog usage I've manually added some recent release information.

docs(Changelog): add recent releases to changelog

---

terminus-ui/scss/helpers/_z-index.scss
terminus-ui/select/src/select.component.scss
terminus-ui/select/src/select.component.spec.ts
terminus-ui/select/src/select.component.ts

Also cleaned up the imports by removing the ones we aren't using.
ISSUES CLOSED: #1227

fix(Select): shift+arrow will select multiple

---

terminus-ui/validation-messages/src/validation-messages.service.ts
terminus-ui/validation-messages/src/validation-messages.services.spec.ts

- Tests are more lenient on phrasing
- Most messages use "must"
- Removed messages for the validators that were deprecated in v11.
ISSUES CLOSED: #1190

chore(ValidationMessages): phrasing is aligned

---

terminus-ui/input/src/input.module.ts

revert(Input): remove BrowserAnimationsModule that was added in error

---

demo/app/components/csv-entry/csv-entry.component.html
demo/app/components/csv-entry/csv-entry.component.ts
terminus-ui/csv-entry/src/csv-entry.component.spec.ts
terminus-ui/csv-entry/src/csv-entry.component.ts

This will enable users to enter cell content containing quotes and commas.
ISSUES CLOSED: #1427
- Add ability in demo to download file
- Add support for double quotes and commas within csv content

fix(CSVEntry): now encapsulating cell content and escaping quotes

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

GitHub wasn't picking up our new issue templates. Apparently there is a different format needed. (our original issue was based off of how Material's looked)
These two templates should be selectable by users and will replace our existing templates if they work.
I'm not sure how they work alongside our existing default template. After Wendy's PR gets merged, I'll merge this and we will see. I will take point on merging them together and cleaning up as needed.
> To be included in the community profile checklist, issue templates must be located in the `.github/ISSUE_TEMPLATE` folder and contain valid `name:` and `about:` YAML front matter.

chore: Update GitHub's built-in issue templates

---

demo/app/components/date-range/date-range.component.html
terminus-ui/date-range/src/date-range.component.md
terminus-ui/date-range/src/date-range.component.spec.ts
terminus-ui/date-range/src/date-range.component.ts
terminus-ui/date-range/testing/src/test-components.ts

💥 BREAKING CHANGE 💥 
ts-date-range instances will have to update \`change\` to \`dateRangeChange\`
Migration notes:
Update <ts-date-range> by replacing `change` with `dateRangeChange`
```typescript
before
<ts-date-range
(change)="myDateRange($event)"
</ts-date-range>
after
<ts-date-range
(dateRangeChange)="myDateRange($event)"
</ts-date-range>
```
ISSUES CLOSED: #1361

fix(DateRange): *BREAKING CHANGE* dateRangeChange is now the emitter name

---

terminus-ui/date-range/src/date-range.component.ts

BREAKING CHANGE: Interface no longer supports `null`.
use undefined instead
ISSUES CLOSED: #1434

chore(DateRange): null portion of interface is deprecated

---

demo/app/components/button/button.component.html
demo/app/components/confirmation/confirmation.component.html
demo/app/components/expansion-panel/expansion-panel.component.html
demo/app/components/icon-button/icon-button.component.html
demo/app/components/icon-button/icon-button.component.ts
demo/app/components/menu/menu.component.html
terminus-ui/button/src/button.component.html
terminus-ui/button/src/button.component.spec.ts
terminus-ui/button/src/button.component.ts
terminus-ui/checkbox/src/checkbox.component.ts
terminus-ui/confirmation/src/confirmation-overlay.component.html
terminus-ui/confirmation/src/confirmation.directive.md
terminus-ui/confirmation/src/confirmation.directive.spec.ts
terminus-ui/confirmation/src/confirmation.directive.ts
terminus-ui/csv-entry/src/csv-entry.component.html
terminus-ui/csv-entry/src/csv-entry.component.spec.ts
terminus-ui/expansion-panel/src/expansion-panel.component.md
terminus-ui/file-upload/src/file-upload.component.html
terminus-ui/icon-button/src/icon-button.component.html
terminus-ui/icon-button/src/icon-button.component.md
terminus-ui/icon-button/src/icon-button.component.spec.ts
terminus-ui/icon-button/src/icon-button.component.ts
terminus-ui/login-form/src/login-form.component.html
terminus-ui/login-form/src/login-form.component.ts
terminus-ui/menu/src/menu.component.md
terminus-ui/navigation/src/navigation.component.ts
terminus-ui/paginator/src/paginator.component.html
terminus-ui/search/src/search.component.html

:boom: Breaking Change :boom:
Migration notes:
- the clickEvent change emitter name has been changed to `clicked` to align with the past tense naming convention of other change emitters
- this affects `ts-button` and `ts-icon-button`
- to implement, simply change clickEvent to `clicked`:
```typescript
// before:
<ts-button>    
(clickEvent)="myClick($event)"
>Click Me!</ts-button>
// after:
<ts-button>    
(clicked)="myClick($event)"
>Click Me!</ts-button>
```

chore(Button): *BREAKING CHANGE* clicked is now emitter name

---

demo/app/components/card/card.component.html
terminus-ui/card/src/card.component.html
terminus-ui/card/src/card.component.md
terminus-ui/card/src/card.component.spec.ts
terminus-ui/card/src/card.component.ts

💥 BREAKING CHANGE 💥 
Card will have to use isDisabled instead of disabled
Migration notes:
- replace `disabled` with `isDisabled`
```typescript
before
<ts-card [disabled]="true">
Disabled Card
</ts-card>
after
<ts-card [isDisabled]="true">
Disabled Card
</ts-card>
```
ISSUES CLOSED: #1267

chore(Card): *BREAKING CHANGE* removed \`disabled\` input

---

demo/app/components/select/select.component.html
terminus-ui/select/src/select.component.html
terminus-ui/select/src/select.component.scss

ISSUES CLOSED: #1451
Issue was related to the z-index change (updated z-index was below the panel container).

fix(Select): fix for missing filter input

---

terminus-ui/loading-overlay/src/loading-overlay.directive.ts

When using the async pipe and a nested value the portal could be reinitialized without first tearing down the portal
ISSUES CLOSED: #1455

fix(LoadingOverlay): fix for portal already loaded error
